### PR TITLE
fix bug of reading line ending with `\r\n`

### PR DESCRIPTION
**Pull request by shenwei356**
When lines were ended with `\r\n`, error occurred:

```
no data found in file test.csv
```

So I just delete the `\r`.

### CODE REVIEW

**Comment by mzimmerman** [comment]
Woops!  I don't typically deal with windows files so I missed this. I'll add this, but could you also submit a test?

**Comment by shenwei356** [comment]
@mzimmerman  a simle test file could be easily generated with shell:'

```
echo -en "a,b\r\n1,2\r\n"
```

**Comment by shenwei356** [comment]
BTW, I wrote a CSV/TSV toolkit using your package. You may try it.

[csvtk](https://github.com/shenwei356/csvtk) -- Another cross-platform, efficient, practical and pretty CSV/TSV toolkit in Golang

Example:

```
$ echo -en "a,b\r\n1111,23333\r\n" | csvtk pretty
a      b
1111   23333
```

**Comment by mzimmerman** [comment]
So I'm not sure this was the issue.  There _is_ a [test](https://github.com/mzimmerman/multicorecsv/blob/master/multicorecsv_test.go#L40) for this already and I believe it is all handled by encoding/csv.  

I also don't see that error "no data found in file" anywhere in multicorecsv.  Was that in your code?

**Comment by shenwei356** [comment]
A test case of blanking line of `\r\n` is added in #2 .

Looking back this pull request, deleting the `\r` character is the simplest and also a robust solution. 

And another question, did the codes from line [multicorecsv.go#L203](https://github.com/mzimmerman/multicorecsv/blob/master/multicorecsv.go#L203) to L217 were carefully written to handle Unicode?

**Comment by mzimmerman** [comment]
I'd like to leave the handling of \r to the underlying encoding/csv as much as possible since it's already doing it.  However, there is the explicit case of the blank line to handle since the way multicore works it does end up having an issue.  So I've fixed it in a slightly different way in 350b5af71b665402277ff987abcf091e51f24b7e.

Yes, multicorecsv should handle Unicode just fine as I'm using the underlying standard library to read rune (proper Unicode support) (to my knowledge as least!)

I usually use column to do what your example of csvtk is doing, however I looked at csvtk and it's got some pretty advanced features!  I'll have to try it out, thanks!

**Pull request merged**
